version: "3"
services:
  imageMongoDb:
    image: mongo:latest
    container_name: imageMongoDb
    networks:
      - gateway
    ports:
      - "27017:27017"
    volumes:
      - ../../../mongo/data/db:/data/db
  prueba-springboot:
    image: prueba-springboot:1.0
    container_name: prueba-springboot
    networks:
      - gateway
    ports:
      - "8080:8080"
    links:
      - imageMongoDb
networks:
  gateway:
    driver: "bridge"